### ISSUE TITLE
Pass `--mpv-speed=1.0` to celluloid to play live streams at normal speed

### ISSUE THREAD

**Issue by rassoc** [d-k-bo/televido#1]
Setting celluloid as the default video player in televido while using a mpv config file with a faster video playback speed such as 1.75x leads to constant pausing and me having to manually adjust the speed each time I open a live stream.

Celluloid allows overwriting the mpv-defined playback speed via arg: `celluloid --mpv-speed=1.0 $FILENAME`. Would it be possible for televido to pass that option along for live streaming? 

Feel free to close the issue if you find it to be too esoteric to consider.

Thanks for releasing televido, really like it so far!

**Comment by d-k-bo** [comment]
Thanks for your request. While I think your use case is too specific to be implemented in Televido itself, it shows a limitation that could be relevant in other scenarios as well. 

Televido currently uses [DBus activiation](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s08.html) via the `Open` method to start video playback. It currently uses a hardcoded list of players that are known to be DBus activatable video players.

I think it would be a good idea if there was some way to use a video player that isn't in that list. This would also allow setting arbitrary options in a wrapper script.

**Comment by d-k-bo** [comment]
f1e27eb added support for custom video players and was released in version 0.1.2. You can create a wrapper script that starts celluloid with custom options to set the playback speed. See https://github.com/d-k-bo/televido#how-can-i-use-a-different-video-player--use-a-player-with-custom-options

**Comment by rassoc** [comment]
Thanks a lot, really appreciated!
