### ISSUE TITLE
Add an option to access prereleased shows

### ISSUE THREAD

**Issue by edisso999** [d-k-bo/televido#12]
MediathekViewWeb shows prereleased entries in the results. Televido only shows already released entries (date today and older).

Example (as of 20. May):

Letzte Spur Berlin

Televido shows episode from 17.5.2024

MVW shows (coming) episode from 24.5.2024

**Comment by d-k-bo** [comment]
You are right, “future“ shows are currently not included in the results. I'll add an option to include them when I rewrite the search section (#10).
