### ISSUE TITLE
[Bug] App doesn't accept org.videolan.VLC even though it has DBus

### ISSUE THREAD

**Issue by Humam-Hamdan** [d-k-bo/televido#19]
when i copy the link and paste it in vlc it works, should i be calling a different function of the app?

**Comment by d-k-bo** [comment]
VLC doesn't support DBus Activation as far as I can tell. You can try to create a wrapper script using [dbus-activatable-wrapper](https://github.com/d-k-bo/dbus-activatable-wrapper), but note that this is just a hack.

You can check that a program is DBus activatable by looking at the output the following command which lists all DBus activatable programs:

    dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.ListActivatableNames

If you are using the Televido Flatpak, make sure to grant it the required permissions. See https://github.com/d-k-bo/televido?tab=readme-ov-file#how-can-i-use-a-different-video-player--use-a-player-with-custom-options

**Comment by Humam-Hamdan** [comment]
Ok thank you, used celluiod in the end.
