### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by julianfairfax** [d-k-bo/televido#2]
The window is a bit too wide to be used on mobile screens. It also doesn't declare itself as supporting mobile devices, so it doesn't show on mobile home screens. Otherwise, it works great on those devices. This issue is to address the two issues.

**Comment by d-k-bo** [comment]
I'll look into it. Do you know the typical (logical) resolution of Linux phones or do you have any resources about screen sizes that mobile apps should support?

**Comment by julianfairfax** [comment]
I don't have those myself. But you might be able to find them somewhere by searching for terms such as "mobile Linux" or "Phosh" [something]. Either way though. The minimum size of Televido is only slightly too big for mobile phone screens, as you can see [here](https://linuxrocks.online/@linuxphoneapps/111291805171539855).

**Comment by d-k-bo** [comment]
FWIW, I found the following recommendation in the [GNOME Human Interface Guidelines](https://developer.gnome.org/hig/guidelines/adaptive.html#small-size-handling):

> Apps that are appropriate for a phone form factor should scale down to 360×294px.

I am working on implementing this guideline and fixing some other problems on smaller screens.

**Comment by d-k-bo** [comment]
a7aa3404 added support for mobile devices and was released in version 0.1.3.
